# Generated by Django 2.1.3 on 2018-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.AutoField(primary_key=True, serialize=False)),
                ('tail_number', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'aircraft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_id', models.AutoField(primary_key=True, serialize=False)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('airline_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Flight delay',
                'verbose_name_plural': 'Flight delays',
                'db_table': 'airline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('airport_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=3)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Flight delay',
                'verbose_name_plural': 'Flight delays',
                'db_table': 'airport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_year', models.IntegerField()),
                ('time_month', models.IntegerField()),
                ('time_day', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('flight_number', models.IntegerField()),
                ('scheduled_departure', models.IntegerField()),
                ('departure_time', models.CharField(max_length=50)),
                ('departure_delay', models.CharField(max_length=50)),
                ('taxi_out', models.CharField(max_length=50)),
                ('wheels_off', models.CharField(max_length=50)),
                ('scheduled_time', models.CharField(max_length=50)),
                ('elapsed_time', models.CharField(max_length=50)),
                ('air_time', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('wheels_on', models.CharField(max_length=50)),
                ('taxi_in', models.CharField(max_length=50)),
                ('scheduled_arrival', models.IntegerField()),
                ('arrival_time', models.CharField(max_length=50)),
                ('arrival_delay', models.CharField(max_length=50)),
                ('diverted', models.IntegerField()),
                ('cancelled', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Flight delay',
                'verbose_name_plural': 'Flight delays',
                'db_table': 'flight',
                'managed': False,
            },
        ),
    ]
